Create Log Analytics workspace. ...
Enable container insights. ...
Configure collection from Prometheus. ...
Collect resource logs. ...
Level 1 - Cluster level components. ...
Level 2 - Managed AKS components. ...
Resource logs.

https://lenfanceenevolution-tst.unicef.org  ---> https://changingchildhood-tst.unicef.org/es/introduction 